
# @baseurl=https://ecommerce-production-59b6.up.railway.app/
# @baseurl1=https://e-commerce-w51c.onrender.com/
# @baseurl2=http://localhost:3003/
# @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NDgwMjg4M2IyMzVjOTAzMzUxODA4NTkiLCJpYXQiOjE2ODYxNDg5MTl9.s3cA2YI29N3CAZbfcZeJCM1HFLg7zvv_w-CysjncrdA
POST http://localhost:3003/auth/signUp
Content-Type: application/json

{
    "name":"vaibhav kumar",
    "email":"vaibhavtezan@gmail.com",
    "password":"1234567",
    "role":"Admin",
    "phoneNumber":"8930485009"
}

###


POST http://localhost:3003/auth/emailVerification
Content-Type: application/json

{
    "email":"vaibhavtezan@gmail.com",
    "otp":"520706"
}



###
POST http://localhost:3003/auth/login
Content-Type: application/json

{
    "email":"vaibhavtezan@gmail.com",
    "password":"1234567"
}



###
POST  http://localhost:3003/auth/changePassword
Content-Type: application/json
Authorization: bearer 
{
    "oldPassword":"123456",
    "newPassword":"1234567"
}
###
POST  http://localhost:3003/auth/logout
Content-Type: application/json
Authorization: bearer 
####
POST http://localhost:3003/product/
Content-Type: application/json
Authorization: bearer 
    "Title":"mango 2",
    "Description":"mango2 is more delicious ",
    "Price":20,
    "Availability":true,
    "Category":"fruits"
}
###

GET http://localhost:3003/product/
Content-Type: application/json
Authorization: bearer 

###

PATCH http://localhost:3003/product/
Content-Type: application/json 

{
    "Productid":"64802f2507d6a2961cc02192",
    "Title":"cake",
    "Description":"cake is very delicious ",
    "Price":2000,
    "Availability":true,
    "Category":"Dairy"
}

###
DELETE http://localhost:3003/product/deleteProduct
Content-Type: application/json
Authorization: bearer
{
    "ProductId":"6480cd0f2ee7fd78ae092a0b"
}
###
POST http://localhost:3003/userCart/
Content-Type: application/json
Authorization: bearer 

{
    "products":[{
      "productId": "648195fb63360ec7537b08b7",
      "quantity": 2
     },{
      "productId": "6481961363360ec7537b08bb",
      "quantity": 4
     }]
}
  
###
GET  http://localhost:3003/cart/showCart
Content-Type: application/json
Authorization: bearer 



###
POST http://localhost:3003/orders/placeOrder
Content-Type: application/json
Authorization: bearer 

{
    "Address":"gurgaon"
}
###
GET  http://localhost:3003/orders/showOrder
Content-Type: application/json
Authorization: bearer 